"use strict";
exports.__esModule = true;
var model_1 = require("./model");
var Vasyl = new model_1.Deputy(78, 179, 'Stethem', 'Vasyl', 45, true, 55000);
var Natalia = new model_1.Deputy(55, 175, 'Ivanova', 'Nata', 21, false, 0);
var Ivan = new model_1.Deputy(88, 189, 'Petriv', 'Ivan', 27, true, 6500);
var Olena = new model_1.Deputy(49, 170, 'Karpa', 'Olena', 24, true, 150600);
var Roman = new model_1.Deputy(88, 186, 'Kum', 'Roman', 21, false, 0);
Vasyl.giveBribe();
var factions = new model_1.Faction([]);
factions.addDeputy(Vasyl);
factions.addDeputy(Natalia);
factions.addDeputy(Olena);
factions.showTheBiggestBriber();
factions.totalBribe();
console.log(factions);
var factions1 = new model_1.Faction([]);
factions1.addDeputy(Ivan);
console.log(factions1);
var factions2 = new model_1.Faction([]);
factions2.addDeputy(Roman);
console.log(factions2);
var Radykalna = new model_1.VerhovnaRada([]);
Radykalna.addFactions(factions);
console.log(Radykalna);
